[package]
name = "sol16"
version = "0.1.0"
authors = ["Tony Cao <tony@benchling.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starter = { path = "../starter" }
